name: Build
on: [push]
jobs:
  build-packages:
    name: Build packages
    timeout-minutes: 30
    runs-on:
      - self-hosted
      - nix
      - general
      - ${{ matrix.runner.runner }}
      - ${{ matrix.runner.size }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - arch: x86_64-linux
            runner: amd64-linux
            size: medium
          - arch: aarch64-linux
            runner: arm64-linux
            size: medium
          - arch: aarch64-darwin
            runner: arm64-darwin
            size: small
    steps:
      - uses: actions/checkout@v4

      - name: Build all packages
        run: |
          nix build -L -v '.#defaultPackage.${{ matrix.runner.arch }}'

      - name: Cache all packages
        env:
          NIX_OUTPUT: .#defaultPackage.${{ matrix.runner.arch }}
        run: |
          nix store sign "${NIX_OUTPUT}" -v -r -k ~/.secrets/nix-cache-private-key
          nix copy -v --to "s3://${NIX_CACHE_BUCKET_NAME}/cache?region=${NIX_CACHE_BUCKET_REGION}&compression=zstd&parallel-compression=true" "${NIX_OUTPUT}"

      # - name: Cache some packages in S3
      #   env:
      #     BIN_ARCH: ${{ matrix.runner.arch }}
      #   shell: nix develop -c bash {0}
      #   run: |
      #     ./cli.sh nix_copy_to_public_bin_cache "${BIN_ARCH}" ecr-credential-provider 1_24

  build-push-images:
    name: Build and push images
    timeout-minutes: 20
    runs-on: 
      - self-hosted
      - nix
      - general
      - ${{ matrix.imageArch }}-linux
      - medium
    needs: [build-packages]
    strategy:
      fail-fast: false
      matrix:
        imageArch: [amd64, arm64]
    defaults:
      run:
        shell: nix develop -c bash {0}
    steps:
      - uses: actions/checkout@v4

      - name: Build all images
        run: |
          ./cli.sh build_all_images ${{ matrix.imageArch }}

      - name: Push all images
        if: github.ref == 'refs/heads/main'
        run: |
          ./cli.sh push_all_single_arch_images ${{ matrix.imageArch }}

  push-manifests:
    name: Build and push multi-arch manifests
    timeout-minutes: 20
    runs-on: [self-hosted, nix, general, arm64-linux, small]
    needs: [build-push-images]
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        shell: nix develop -c bash {0}      
    steps:
      - uses: actions/checkout@v4

      - name: Build and push images
        run: |
          ./cli.sh push_all_manifests
