name: Build all packages
on: [push]
jobs:
  build:
    runs-on: [self-hosted, nix]
    strategy:
      matrix:
        arch:
          - aarch64-linux
          - aarch64-darwin
          - x86_64-linux
          - x86_64-darwin
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Test
        run: |
          cd ./tests
          nix build -L -vv --no-link '.#defaultPackage.${{ matrix.arch }}'

      - name: Build all
        run: nix build -L -vv '.#defaultPackage.${{ matrix.arch }}'

      - name: Cache all
        env:
          NIX_OUTPUT: .#defaultPackage.${{ matrix.arch }}
        run: |
          nix store sign "${NIX_OUTPUT}" -v -r -k ~/.secrets/nix-cache-private-key
          nix copy -v "${NIX_OUTPUT}" --to s3://nixed/cache
