name: Build
on: [push]
jobs:
  build-packages:
    timeout-minutes: 20
    runs-on:
      - self-hosted
      - nix
      - general
      - ${{ matrix.runner.runner }}
      - ${{ matrix.runner.size }}
    strategy:
      matrix:
        runner:
          - arch: x86_64-linux
            runner: amd64-linux
            size: medium
          - arch: aarch64-linux
            runner: arm64-linux
            size: medium
          - arch: aarch64-darwin
            runner: arm64-darwin
            size: small
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          cd ./tests
          nix build -L -v --no-link '.#defaultPackage.${{ matrix.runner.arch }}'

      - name: Build all packages
        run: nix build -L -v '.#defaultPackage.${{ matrix.runner.arch }}'

      - name: Cache all packages
        env:
          NIX_OUTPUT: .#defaultPackage.${{ matrix.runner.arch }}
        run: |
          nix store sign "${NIX_OUTPUT}" -v -r -k ~/.secrets/nix-cache-private-key
          nix copy -v "${NIX_OUTPUT}" --to s3://nixed/cache

  build-push-images:
    timeout-minutes: 20
    runs-on: 
      - self-hosted
      - nix
      - general
      - ${{ matrix.arch.runner }}-linux
      - medium
    needs: [build-packages]
    env:
      IMAGE_REPOSITORY: public.ecr.aws/shopstic
    strategy:
      matrix:
        imageArch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Build all images
        shell: nix develop -v -c bash {0}
        run: |
          ./cli.sh build_all_images ${{ matrix.imageArch }}

      - name: Login
        if: github.ref == 'refs/heads/main'
        shell: nix develop -v -c bash {0}
        run: |-
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin "${IMAGE_REPOSITORY}"

      - name: Push all images
        if: github.ref == 'refs/heads/main'
        shell: nix develop -v -c bash {0}
        run: |
          ./cli.sh push_all_single_arch_images ${{ matrix.imageArch }}

  push-manifests:
    timeout-minutes: 20
    runs-on: [self-hosted, nix, general, arm64-linux, small]
    needs: [build-push-images]
    if: github.ref == 'refs/heads/main'
    env:
      IMAGE_REPOSITORY: public.ecr.aws/shopstic
    steps:
      - uses: actions/checkout@v3

      - name: Login
        shell: nix develop -v -c bash {0}
        run: |-
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin "${IMAGE_REPOSITORY}"

      - name: Build and push images
        shell: nix develop -v -c bash {0}
        run: |
          ./cli.sh push_all_manifests
